spring:
  application:
    name: rating-service
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:change-me}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health
